package FreeTime.greenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CSDNCACHE".
 */
public class CSDNCache {

    private Long id;
    private String title;
    private String date;
    private String imgLink;
    private String link;
    private String content;
    private String urlType;

    public CSDNCache() {
    }

    public CSDNCache(Long id) {
        this.id = id;
    }

    public CSDNCache(Long id, String title, String date, String imgLink, String link, String content, String urlType) {
        this.id = id;
        this.title = title;
        this.date = date;
        this.imgLink = imgLink;
        this.link = link;
        this.content = content;
        this.urlType = urlType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getImgLink() {
        return imgLink;
    }

    public void setImgLink(String imgLink) {
        this.imgLink = imgLink;
    }

    public String getLink() {
        return link;
    }

    public void setLink(String link) {
        this.link = link;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getUrlType() {
        return urlType;
    }

    public void setUrlType(String urlType) {
        this.urlType = urlType;
    }

}
