package FreeTime.greenDao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import FreeTime.greenDao.ImageCache;
import FreeTime.greenDao.CSDNCache;

import FreeTime.greenDao.ImageCacheDao;
import FreeTime.greenDao.CSDNCacheDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig imageCacheDaoConfig;
    private final DaoConfig cSDNCacheDaoConfig;

    private final ImageCacheDao imageCacheDao;
    private final CSDNCacheDao cSDNCacheDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        imageCacheDaoConfig = daoConfigMap.get(ImageCacheDao.class).clone();
        imageCacheDaoConfig.initIdentityScope(type);

        cSDNCacheDaoConfig = daoConfigMap.get(CSDNCacheDao.class).clone();
        cSDNCacheDaoConfig.initIdentityScope(type);

        imageCacheDao = new ImageCacheDao(imageCacheDaoConfig, this);
        cSDNCacheDao = new CSDNCacheDao(cSDNCacheDaoConfig, this);

        registerDao(ImageCache.class, imageCacheDao);
        registerDao(CSDNCache.class, cSDNCacheDao);
    }
    
    public void clear() {
        imageCacheDaoConfig.getIdentityScope().clear();
        cSDNCacheDaoConfig.getIdentityScope().clear();
    }

    public ImageCacheDao getImageCacheDao() {
        return imageCacheDao;
    }

    public CSDNCacheDao getCSDNCacheDao() {
        return cSDNCacheDao;
    }

}
