package FreeTime.greenDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "IMAGE_CACHE".
 */
public class ImageCache {

    private Long id;
    private String data;
    private String totalDataNum;
    private String urlType;

    public ImageCache() {
    }

    public ImageCache(Long id) {
        this.id = id;
    }

    public ImageCache(Long id, String data, String totalDataNum, String urlType) {
        this.id = id;
        this.data = data;
        this.totalDataNum = totalDataNum;
        this.urlType = urlType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public String getTotalDataNum() {
        return totalDataNum;
    }

    public void setTotalDataNum(String totalDataNum) {
        this.totalDataNum = totalDataNum;
    }

    public String getUrlType() {
        return urlType;
    }

    public void setUrlType(String urlType) {
        this.urlType = urlType;
    }

}
